import assert from 'node:assert/strict';
import test from 'node:test';
import { getSuggestions, resolveBridgeConfiguration, resolveModelConfiguration, validateSuggestions } from '../lib/suggestions.js';
import { parseSelection } from '../lib/selection.js';

const prompt = 'Implement this feature while preserving the existing architecture, adding meaningful validation, handling errors, and testing the finished user-facing workflow.';
test('validateSuggestions accepts strict 3-4 word titles and complete prompts', () => { const suggestions = validateSuggestions({ suggestions: ['Project Health Summary', 'Guided First Run', 'Actionable Error Messages', 'Focused Test Coverage'].map((title) => ({ title, prompt })) }); assert.equal(suggestions.length, 4); });
test('validateSuggestions rejects invalid model output', () => { assert.throws(() => validateSuggestions({ suggestions: [{ title: 'Too Short', prompt }] }), /4 to 6/); assert.throws(() => validateSuggestions({ suggestions: Array.from({ length: 4 }, () => ({ title: 'Bad Title', prompt })) }), /3-4 words/); });
test('mock suggestions use strict 3-4 word titles for every mode', async () => { for (const mode of ['balanced', 'growth', 'ux', 'technical', 'wild']) { const suggestions = await getSuggestions({ name: 'dirgest' }, { mock: true, mode }); assert.equal(suggestions.length, 5); for (const suggestion of suggestions) assert.ok(suggestion.title.split(/\s+/).length >= 3 && suggestion.title.split(/\s+/).length <= 4, `${mode}: ${suggestion.title}`); } });
test('suggestion modes produce distinct deterministic ideas', async () => { const project = { name: 'dirgest' }; const balanced = await getSuggestions(project, { mock: true }); const growth = await getSuggestions(project, { mock: true, mode: 'growth' }); assert.notDeepEqual(growth, balanced); await assert.rejects(getSuggestions(project, { mock: true, mode: 'invalid' }), /Unknown suggestion mode/); });
test('ModelHitch credential configuration is preferred over the default provider', () => { const hitch = { providers: [{ id: 'openai', defaultModel: 'gpt-4o-mini', apiKeyEnvVar: 'OPENAI_API_KEY' }, { id: 'groq', defaultModel: 'llama-3.3-70b-versatile', apiKeyEnvVar: 'GROQ_API_KEY' }] }; assert.deepEqual(resolveModelConfiguration(hitch, { GROQ_API_KEY: 'configured-key' }), { provider: 'groq', model: 'llama-3.3-70b-versatile', usesModelHitchConfiguration: true }); });
test('dirgest model overrides win and no ModelHitch configuration preserves OpenAI defaults', () => { const hitch = { providers: [{ id: 'openai', defaultModel: 'gpt-4o-mini', apiKeyEnvVar: 'OPENAI_API_KEY' }, { id: 'groq', defaultModel: 'llama-3.3-70b-versatile', apiKeyEnvVar: 'GROQ_API_KEY' }] }; assert.deepEqual(resolveModelConfiguration(hitch, {}), { provider: 'openai', model: 'gpt-4o-mini', usesModelHitchConfiguration: false }); assert.deepEqual(resolveModelConfiguration(hitch, { GROQ_API_KEY: 'configured-key', DIRGEST_PROVIDER: 'openai', DIRGEST_MODEL: 'gpt-4.1-mini' }), { provider: 'openai', model: 'gpt-4.1-mini', usesModelHitchConfiguration: false }); });
test('bridge model configuration gives the global override precedence', () => { const catalog = { data: [{ id: 'other-model' }, { id: 'big-pickle' }] }; assert.equal(resolveBridgeConfiguration(catalog, { DIRGEST_MODEL: 'explicit-model', DIRGEST_BRIDGE_MODEL: 'bridge-model' }).model, 'explicit-model'); assert.equal(resolveBridgeConfiguration(catalog, { DIRGEST_BRIDGE_MODEL: 'bridge-model' }).model, 'bridge-model'); assert.deepEqual(resolveBridgeConfiguration(catalog, {}), { provider: 'openai', model: 'big-pickle', credentials: { apiKey: 'sk-bridge-local', baseUrl: 'http://127.0.0.1:3939/v1' }, usesModelHitchConfiguration: true }); assert.equal(resolveBridgeConfiguration({ data: [] }, {}), null); });
test('parseSelection handles prompt, all, and quit choices', () => { assert.equal(parseSelection('2', 5), 1); assert.equal(parseSelection('a', 5), 'all'); assert.equal(parseSelection('q', 5), 'quit'); assert.equal(parseSelection('9', 5), null); });