import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
function Field({ label, value, mono }) {
    return (_jsxs("div", { className: "context-field", children: [_jsx("div", { className: "context-label", children: label }), _jsx("div", { className: `context-value ${!value ? 'empty' : ''}`, style: mono ? { fontFamily: 'var(--font-mono)' } : undefined, children: value || 'Not detected' })] }));
}
function DepTags({ label, deps, className }) {
    if (deps.length === 0)
        return null;
    return (_jsxs("div", { style: { marginBottom: '0.75rem' }, children: [_jsx("div", { className: "context-label", style: { marginBottom: '0.375rem' }, children: label }), _jsx("div", { className: "dep-list", children: deps.map((d) => (_jsx("span", { className: `dep-tag ${className || ''}`, children: d }, d))) })] }));
}
export function ProjectView({ context, onGenerateSuggestions }) {
    return (_jsxs("div", { children: [_jsxs("div", { className: "card", children: [_jsx("div", { className: "card-header", children: _jsx("span", { className: "card-title", children: "What Dirgest thinks this is" }) }), _jsxs("div", { className: "context-grid", children: [_jsx(Field, { label: "Name", value: context.name }), _jsx(Field, { label: "Language", value: context.detectedLanguage }), _jsx(Field, { label: "Framework", value: context.detectedFramework }), _jsx(Field, { label: "Project type", value: context.detectedProjectType }), _jsx(Field, { label: "Files", value: String(context.metadata.fileCount) }), _jsx(Field, { label: "Description", value: context.metadata.description ?? null })] })] }), context.entryPoints.length > 0 && (_jsxs("div", { className: "card", children: [_jsx("div", { className: "card-header", children: _jsx("span", { className: "card-title", children: "Entry points" }) }), _jsx("div", { className: "dep-list", children: context.entryPoints.map((ep) => (_jsx("span", { className: "dep-tag", children: ep }, ep))) })] })), (context.dependencies.firebase.length > 0 ||
                context.dependencies.aws.length > 0 ||
                context.dependencies.ai.length > 0) && (_jsxs("div", { className: "card", children: [_jsx("div", { className: "card-header", children: _jsx("span", { className: "card-title", children: "Notable dependencies" }) }), _jsx(DepTags, { label: "Firebase", deps: context.dependencies.firebase, className: "firebase" }), _jsx(DepTags, { label: "AWS", deps: context.dependencies.aws, className: "aws" }), _jsx(DepTags, { label: "AI / ML", deps: context.dependencies.ai, className: "ai" })] })), context.summary && (_jsxs("div", { className: "card", children: [_jsx("div", { className: "card-header", children: _jsx("span", { className: "card-title", children: "Analysis" }) }), _jsx("div", { className: "summary-text", children: context.summary })] })), _jsxs("div", { className: "card", children: [_jsxs("div", { className: "card-header", children: [_jsx("span", { className: "card-title", children: "Source files" }), _jsxs("span", { style: { fontSize: '0.75rem', color: 'var(--text-2)' }, children: [context.files.length, " files, sorted by priority"] })] }), _jsx("div", { className: "file-list", children: context.files.map((f) => (_jsxs("div", { className: "file-item", children: [_jsx("span", { className: "file-priority", children: f.priority }), _jsx("span", { children: f.path })] }, f.path))) })] }), _jsx("div", { style: { marginTop: '1.5rem', display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }, children: ['balanced', 'growth', 'ux', 'technical', 'wild'].map((mode) => (_jsx("button", { className: "btn", onClick: () => onGenerateSuggestions(mode), children: mode }, mode))) })] }));
}
